# Generated by Django 4.2.4 on 2023-08-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
